# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x03gcs\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n\x10telemetryRequest\"\xe6\x01\n\x11telemetryResponse\x12\x17\n\x04mode\x18\x01 \x01(\x0e\x32\t.gcs.Mode\x12\x0f\n\x07\x62\x61ttery\x18\x02 \x01(\x02\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1a\n\x07qr_side\x18\x06 \x01(\x0e\x32\t.gcs.Side\x12\r\n\x05\x64\x65pth\x18\x07 \x01(\x02\x12\x11\n\tfc_status\x18\x08 \x01(\x08\x12\x15\n\rsensor_status\x18\t \x01(\x08*\"\n\x04Mode\x12\n\n\x06MANUAL\x10\x00\x12\x0e\n\nAUTONOMOUS\x10\x01*1\n\x04Side\x12\x05\n\x01\x41\x10\x00\x12\x05\n\x01\x42\x10\x01\x12\x05\n\x01\x43\x10\x02\x12\x05\n\x01\x44\x10\x03\x12\r\n\tNOT_FOUND\x10\x04\x32K\n\x06Server\x12\x41\n\x0cgetTelemetry\x12\x15.gcs.telemetryRequest\x1a\x16.gcs.telemetryResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODE']._serialized_start=307
  _globals['_MODE']._serialized_end=341
  _globals['_SIDE']._serialized_start=343
  _globals['_SIDE']._serialized_end=392
  _globals['_TELEMETRYREQUEST']._serialized_start=54
  _globals['_TELEMETRYREQUEST']._serialized_end=72
  _globals['_TELEMETRYRESPONSE']._serialized_start=75
  _globals['_TELEMETRYRESPONSE']._serialized_end=305
  _globals['_SERVER']._serialized_start=394
  _globals['_SERVER']._serialized_end=469
# @@protoc_insertion_point(module_scope)
